#!/bin/bash
#
# pre-commit (dotfiles)

# |1| Exclude TASKS.md from public branch

FILE_TO_EXCLUDE="TASKS.md"
EXCLUDE_BRANCH="public"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Unstage TASKS.md when committing to branch `public`
if [[ "$CURRENT_BRANCH" == "$EXCLUDE_BRANCH" ]]; then
  if git diff --cached --name-only | grep -q "^$FILE_TO_EXCLUDE$"; then
    git reset HEAD -- "$FILE_TO_EXCLUDE"
    echo "Warning: '$FILE_TO_EXCLUDE' has been unstaged on branch '$EXCLUDE_BRANCH' and will not be committed."
  fi
fi

# Allow the commit to proceed
exit 0
